blog/urls.py
# _*_ encoding:utf-8 _*_
__author__ = "ludada"
__date__ = "2018/10/28 21:28"
from django.urls import path
from . import views

# start with blog
urlpatterns = [
    # http://localhost:8000/blog/
    path('', views.blog_list, name='blog_list'),
    path('<int:blog_pk>', views.blog_detail, name="blog_detail"),
    path('type/<int:blog_type_pk>', views.blog_type_list, name="blog_type_list"),
    path('date/<int:year>/<int:month>', views.blog_dates_list, name="blog_date_list"),
]

ludadablog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from ludadablog.settings import MEDIA_ROOT
from django.views.static import serve
urlpatterns = [
    re_path(r'media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('captcha/', include('captcha.urls')),
    path('blog/', include('blog.urls')),
    path('comment/', include('comment.urls')),
    path('likes/', include('likes.urls')),
    re_path('active/(?P<active_code>.*)/', views.active, name='user_active'),
    path('login/', views.login, name='login'),
    path('login_for_medal/', views.login_for_medal, name='login_for_medal'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
]

blog/models.py
from django.db import models

from django.conf import settings
from django.contrib.contenttypes.fields import GenericRelation
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.contenttypes.models import ContentType
from read_record.models import ReadNumExpandMethod, ReadDetail, ReadNum
from django.db.models.fields import exceptions


class BlogType(models.Model):
    type_name = models.CharField(max_length=15)

    def __str__(self):
        return self.type_name


class Blog(models.Model, ReadNumExpandMethod):
    title = models.CharField(max_length=50)
    blog_type = models.ForeignKey(BlogType, on_delete=models.CASCADE)
    content = RichTextUploadingField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="blog/%Y/%m", max_length=300, verbose_name=u"封面图", blank=True, null=True)
    read_details = GenericRelation(ReadDetail)
    created_time = models.DateTimeField(auto_now_add=True)
    last_updated_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "<Blog: %s>" % self.title

    class Meta:
        ordering = ['-created_time']
        verbose_name = u'博客'
        verbose_name_plural = verbose_name

    def get_read_num(self):
        ct = ContentType.objects.get_for_model(Blog)
        try:
            readnum = ReadNum.objects.get(content_type=ct, object_id=self.id)
            return readnum.read_num
        except exceptions.ObjectDoesNotExist:
            return 0

templates/active_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>链接失效</p>
</body>
</html>

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block header_extends %}{% endblock %}
    <title>{% block title %}Ludada{% endblock %}</title>
</head>
<body>

    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
        <div class="navbar-header">
            <a href="" class="navbar-brand"></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                  <li class="{% block nav_home_active %}{% endblock %}"><a href="{% url 'home' %}">首页</a></li>
                  <li class="{% block nav_blog_active %}{% endblock %}"><a href="{% url 'blog_list' %}">博客</a></li>
              </ul>
             <ul class="nav navbar-nav navbar-right">
                    {% if not user.is_authenticated %}
                        <li>
                            <a href="{% url 'login' %}?from={{ request.get_full_path }}">登录</a>
                        </li>
                        <li>
                            <a href="{% url 'register' %}?from={{ request.get_full_path }}">注册</a>
                        </li>
                    {% else %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">{{ user.username }} <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="">个人资料</a></li>
                                <li><a href="{% url 'logout' %}">退出</a></li>
                            </ul>
                        </li>
                    {% endif %}
                </ul>
        </div>



    </div>
    </div>

    {% block content %}{% endblock %}
    {% block script_extends %}{% endblock %}
<script type="text/javascript" src="{% static 'js/canvas-nest.js' %}"></script>

<script type="text/javascript">

    /*
     * https://www.xianjieo.cn
     */
    !function (e, t, a) {
        function r() {
            for (var e = 0; e < s.length; e++) s[e].alpha <= 0 ? (t.body.removeChild(s[e].el), s.splice(e, 1)) : (s[e].y--, s[e].scale += .004, s[e].alpha -= .013, s[e].el.style.cssText = "left:" + s[e].x + "px;top:" + s[e].y + "px;opacity:" + s[e].alpha + ";transform:scale(" + s[e].scale + "," + s[e].scale + ") rotate(45deg);background:" + s[e].color + ";z-index:99999");
            requestAnimationFrame(r)
        }

        function n() {
            var t = "function" == typeof e.onclick && e.onclick;
            e.onclick = function (e) {
                t && t(), o(e)
            }
        }

        function o(e) {
            var a = t.createElement("div");
            a.className = "heart", s.push({
                el: a,
                x: e.clientX - 5,
                y: e.clientY - 5,
                scale: 1,
                alpha: 1,
                color: c()
            }), t.body.appendChild(a)
        }

        function i(e) {
            var a = t.createElement("style");
            a.type = "text/css";
            try {
                a.appendChild(t.createTextNode(e))
            } catch (t) {
                a.styleSheet.cssText = e
            }
            t.getElementsByTagName("head")[0].appendChild(a)
        }

        function c() {
            return "rgb(" + ~~(255 * Math.random()) + "," + ~~(255 * Math.random()) + "," + ~~(255 * Math.random()) + ")"
        }

        var s = [];
        e.requestAnimationFrame = e.requestAnimationFrame || e.webkitRequestAnimationFrame || e.mozRequestAnimationFrame || e.oRequestAnimationFrame || e.msRequestAnimationFrame || function (e) {
            setTimeout(e, 1e3 / 60)
        }, i(".heart{width: 10px;height: 10px;position: fixed;background: #f00;transform: rotate(45deg);-webkit-transform: rotate(45deg);-moz-transform: rotate(45deg);}.heart:after,.heart:before{content: '';width: inherit;height: inherit;background: inherit;border-radius: 50%;-webkit-border-radius: 50%;-moz-border-radius: 50%;position: fixed;}.heart:after{top: -5px;}.heart:before{left: -5px;}"), n(), r()
    }(window, document);
</script>

</body>
</html>

templates/blog_date_list.html
{% extends 'blog_list.html' %}
{% block title %}{{ blog_type.type_name }}{% endblock %}

{% block blog_list_title %}
    日期归档：{{ blogs_with_date }}
    <a href="{% url 'blog_list' %}">查看全部博客</a>
{% endblock %}

templates/blog_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load comment_tags %}
{% block header_extends %}
     <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/blog-list.css' %}">
{% endblock %}
{% block title %}博客列表{% endblock %}
 {% block content %}
    <div class="container body">
    <div class="row">
      <div class="col-xs-12 col-sm-9 col-md-9">
        <div class="panel panel-default">
          <div class="panel-heading">
              {% block blog_list_title %}
              &nbsp;&nbsp;&nbsp;博客列表(一共有{{ blogs|length }}篇博客)
              {% endblock %}
             </div>
          <div class="panel-body">
              {% for blog in page_of_blogs.object_list %}
          <div class="blog-list">
                   <div class="blog-list-item clearfix">
                        <div class="col-xs-4">
                            <div class="blog-img"><a href="{% url 'blog_detail' blog.pk %}"><img src="{{ MEDIA_URL }}{{ blog.image }}"></a></div>
                        </div>
                        <div class="col-xs-8 blog-massage">
                            <div>
                                <a class="blog-title" href="{% url 'blog_detail' blog.pk %}">
                                {{ blog.title }}
                            </a>
                            </div>

                            <div class="info">
                               <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                   <a class="blog-type" href="{% url 'blog_type_list' blog.blog_type.id %}">{{ blog.blog_type }}</a>&nbsp;&nbsp;
                    <span class="glyphicon glyphicon-time" aria-hidden="true"></span>&nbsp;{{ blog.created_time|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;阅读({{ blog.get_read_num }})&nbsp;&nbsp;评论({% get_comment_count blog %})</p>
                <p>{{ blog.content|striptags|truncatechars:36 }}</p>
                            </div>
                        </div>

                    </div>
          </div>
              {% empty %}
                <p>--暂无博客，敬请期待--</p>
                 {% endfor %}
         </div>
          </div>
        </div>

      <div class="hidden-xs col-sm-3 col-md-3">
        <div class="panel panel-default">
          <div class="panel-heading">博客分类</div>
          <div class="panel-body">
            <ul style="list-style-type: none;">
              {% for blog_type in blog_types %}
              <li><a class="blog-bar-type" href="{% url 'blog_type_list' blog_type.pk %}" >{{ blog_type.type_name }}({{ blog_type.blog_set.count }})</a></li>
              {% endfor %}
          </ul>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">日期归档</div>
          <div class="panel-body">
            <ul style="list-style-type: none;">
              {% for blog_date,blog_count in blog_dates.items %}
              <li><a class="blog-bar-type" href="{% url 'blog_date_list' blog_date.year blog_date.month %}">{{ blog_date|date:'Y年m月' }}({{ blog_count }})</a></li>
              {% endfor %}
          </ul>
          </div>
        </div>
      </div>
   </div>
                            <div class="paginator">
                            <ul class="pagination">
                            {% if page_of_blogs.has_previous %}
                                <li class="long"><a href="?{{ page_of_blogs.previous_page_number.querystring }}">上一页</a></li>
                            {% endif %}

                            {% for page in page_of_blogs.pages %}
                                {% if page %}
                                    {% ifequal page page_of_blogs.number %}
                                        <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                                    {% else %}
                                        <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                                    {% endifequal %}
                                {% else %}
                                    <li class="none"><a href="">...</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if page_of_blogs.has_next %}
                                <li class="long"><a href="?{{ page_of_blogs.next_page_number.querystring }}">下一页</a></li>
                            {% endif %}
              </ul>
    </div>
</div>



{% endblock %}
{% block active_blog_list %}active{% endblock %}

templates/blog_type_list.html
{% extends 'blog_list.html' %}
{% block title %}{{ blog_type.type_name }}{% endblock %}

{% block blog_list_title %}
    分类：{{ blog_type.type_name }}
    <a href="{% url 'blog_list' %}">查看全部博客</a>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    我的网站|首页
{% endblock %}

{% block header_extends %}
     <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <script src="http://cdn.hcharts.cn/highcharts/highcharts.js"></script>
{% endblock %}
{% block nav_home_active %}active{% endblock %}

{% block content %}
<div class="container body">
  <div class="row">
  <div class="col-md-3">
  <div class="panel panel-default">
  <div class="panel-heading">阅读排行榜</div>
  <div class="panel-body">
    <div>
    <h3>当天阅读榜</h3>
     {% for today_data in today_read_datas %}
        {{ today_data.content_object.title }}({{ today_data.read_num }})
    {% endfor %}
     </div>
       <div>
        <h3>作天阅读榜</h3>
        {% for yestoday_data in yestoday_read_datas %}
        {{ yestoday_data.content_object.title }}({{ yestoday_data.read_num }})
        {% endfor %}
    </div>
   <div>
        <h3>上周热读榜</h3>
        {% for hot_blog in hot_blog_for_7_day %}
        {{ hot_blog.content_object.title }}({{ hot_blog.read_num }})
        {% endfor %}
    </div>
  </div>
</div>

  </div>
  <div class="col-md-9">
      <h3 class="home-content">欢迎访问我的网站，随便看</h3>
    <!-- 图表容器 DOM -->
    <div id="container"></div>
    <script>
        // 图表配置
        var options = {
            chart: { type: 'line' },
            title: { text: null },
            xAxis: {
                categories: {{ dates|safe }},   // x 轴分类
                tickmarkPlacement: 'on',
            },
            yAxis: {
                title: { text: null },
                labels:{ enabled: false },
                gridLineDashStyle: 'Dash',
            },
            series: [{                              // 数据列
                name: '阅读量',                     // 数据列名
                data: {{ read_nums }}               // 数据
            }],
            plotOptions: {
                line: {
                    dataLabels: {
                        enabled: true
                    }
                }
            },
            legend: { enabled: false },
            credits: { enabled: false },
        };
        // 图表初始化函数
        var chart = Highcharts.chart('container', options);
    </script>


  </div>
</div>
</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    我的网站|登录
{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
    <div class="containter body" style="margin-top: 105px;">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">登录</h3>
                    </div>
                    <div class="panel-body">
                        <form action="" method="POST">
                            {% csrf_token %}
                            {% for field in login_form %}
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                                <p class="text-danger">{{ field.errors.as_text }}</p>
                            {% endfor %}
                            <span class="pull-left text-danger">{{ login_form.non_field_errors }}</span>
                            <input type="submit" value="登录" class="btn btn-primary pull-right">
                        </form>
                    </div>
                </div>                
            </div>
        </div>
    </div>    
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    我的网站|注册
{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
    <div class="containter" style="margin-top: 105px;">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">注册</h3>
                    </div>
                    <div class="panel-body">
                        <form action="" method="POST">
                            {% csrf_token %}
                            {% for field in reg_form %}
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                                <p class="text-danger">{{ field.errors.as_text }}</p>
                            {% endfor %}
                            <span class="pull-left text-danger">{{ reg_form.non_field_errors }}</span>
                            <input type="submit" value="注册" class="btn btn-primary pull-right">
                        </form>
                    </div>
                </div>                
            </div>
        </div>
    </div>    
{% endblock %}